# Generated by Django 5.0.4 on 2024-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsReg',
            new_name='StudentRegistration',
        ),
        migrations.AddField(
            model_name='course',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
